-- Tabele dla aplikacji boatsStats – uruchom w Supabase: SQL Editor → New query → Run
-- Kolejność: najpierw boats_list (referencje), potem boat_availability_*, na końcu example.

-- 1. boats_list (główna lista łodzi)
CREATE TABLE IF NOT EXISTS public.boats_list (
    _id text NOT NULL,
    slug text NOT NULL,
    vat_excluded boolean NOT NULL,
    old_id bigint NOT NULL,
    views bigint NOT NULL,
    title text NOT NULL,
    manufacturer text NOT NULL,
    model text NOT NULL,
    category text NOT NULL,
    category_slug text NOT NULL,
    illustrated boolean NOT NULL,
    marina text NOT NULL,
    country text NOT NULL,
    region text NOT NULL,
    city text NOT NULL,
    flag text NOT NULL,
    captain text NOT NULL,
    sail text NOT NULL,
    "engineType" text NOT NULL,
    "cancellationInsurance" jsonb,
    "totalReviews" bigint NOT NULL,
    "lastCustomer" text NOT NULL,
    rank numeric NOT NULL,
    newboat boolean NOT NULL,
    "reviewsScore" double precision NOT NULL,
    cancellations text,
    thumb text NOT NULL,
    main_img text NOT NULL,
    "boataroundExtra" boolean NOT NULL,
    "charterLoyalty" boolean NOT NULL,
    additional_specials text[] NOT NULL DEFAULT '{}',
    "featuredUsp" jsonb NOT NULL,
    restrictions_covered jsonb,
    "freeBerths" jsonb NOT NULL,
    charter jsonb NOT NULL,
    charter_logo jsonb,
    charter_id text NOT NULL,
    prepayment bigint NOT NULL,
    guarantee_date text,
    "priceFrom" numeric NOT NULL,
    discount text,
    "loyaltyDiscount" bigint NOT NULL,
    currency text NOT NULL,
    "isSmartDeal" boolean NOT NULL,
    preferred_program boolean NOT NULL,
    coordinates numeric[] NOT NULL DEFAULT '{}',
    parameters jsonb NOT NULL,
    charter_rank jsonb NOT NULL,
    usp jsonb DEFAULT '[]'::jsonb,
    "noLicense" jsonb,
    "totalPrice" bigint,
    PRIMARY KEY (_id),
    UNIQUE (slug)
);

-- 2. boat_availability_2025
CREATE TABLE IF NOT EXISTS public.boat_availability_2025 (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text REFERENCES public.boats_list(slug),
    week_1 jsonb,
    week_2 jsonb,
    week_3 jsonb,
    week_4 jsonb,
    week_5 jsonb,
    week_6 jsonb,
    week_7 jsonb,
    week_8 jsonb,
    week_9 jsonb,
    week_10 jsonb,
    week_11 jsonb,
    week_12 jsonb,
    week_13 jsonb,
    week_14 jsonb,
    week_15 jsonb,
    week_16 jsonb,
    week_17 jsonb,
    week_18 jsonb,
    week_19 jsonb,
    week_20 jsonb,
    week_21 jsonb,
    week_22 jsonb,
    week_23 jsonb,
    week_24 jsonb,
    week_25 jsonb,
    week_26 jsonb,
    week_27 jsonb,
    week_28 jsonb,
    week_29 jsonb,
    week_30 jsonb,
    week_31 jsonb,
    week_32 jsonb,
    week_33 jsonb,
    week_34 jsonb,
    week_35 jsonb,
    week_36 jsonb,
    week_37 jsonb,
    week_38 jsonb,
    week_39 jsonb,
    week_40 jsonb,
    week_41 jsonb,
    week_42 jsonb,
    week_43 jsonb,
    week_44 jsonb,
    week_45 jsonb,
    week_46 jsonb,
    week_47 jsonb,
    week_48 jsonb,
    week_49 jsonb,
    week_50 jsonb,
    week_51 jsonb,
    week_52 jsonb,
    week_53 jsonb
);

-- 3. boat_availability_2026
CREATE TABLE IF NOT EXISTS public.boat_availability_2026 (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text REFERENCES public.boats_list(slug),
    week_1 jsonb,
    week_2 jsonb,
    week_3 jsonb,
    week_4 jsonb,
    week_5 jsonb,
    week_6 jsonb,
    week_7 jsonb,
    week_8 jsonb,
    week_9 jsonb,
    week_10 jsonb,
    week_11 jsonb,
    week_12 jsonb,
    week_13 jsonb,
    week_14 jsonb,
    week_15 jsonb,
    week_16 jsonb,
    week_17 jsonb,
    week_18 jsonb,
    week_19 jsonb,
    week_20 jsonb,
    week_21 jsonb,
    week_22 jsonb,
    week_23 jsonb,
    week_24 jsonb,
    week_25 jsonb,
    week_26 jsonb,
    week_27 jsonb,
    week_28 jsonb,
    week_29 jsonb,
    week_30 jsonb,
    week_31 jsonb,
    week_32 jsonb,
    week_33 jsonb,
    week_34 jsonb,
    week_35 jsonb,
    week_36 jsonb,
    week_37 jsonb,
    week_38 jsonb,
    week_39 jsonb,
    week_40 jsonb,
    week_41 jsonb,
    week_42 jsonb,
    week_43 jsonb,
    week_44 jsonb,
    week_45 jsonb,
    week_46 jsonb,
    week_47 jsonb,
    week_48 jsonb,
    week_49 jsonb,
    week_50 jsonb,
    week_51 jsonb,
    week_52 jsonb,
    week_53 jsonb
);

-- 4. boat_availability_2027
CREATE TABLE IF NOT EXISTS public.boat_availability_2027 (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text REFERENCES public.boats_list(slug),
    week_1 jsonb,
    week_2 jsonb,
    week_3 jsonb,
    week_4 jsonb,
    week_5 jsonb,
    week_6 jsonb,
    week_7 jsonb,
    week_8 jsonb,
    week_9 jsonb,
    week_10 jsonb,
    week_11 jsonb,
    week_12 jsonb,
    week_13 jsonb,
    week_14 jsonb,
    week_15 jsonb,
    week_16 jsonb,
    week_17 jsonb,
    week_18 jsonb,
    week_19 jsonb,
    week_20 jsonb,
    week_21 jsonb,
    week_22 jsonb,
    week_23 jsonb,
    week_24 jsonb,
    week_25 jsonb,
    week_26 jsonb,
    week_27 jsonb,
    week_28 jsonb,
    week_29 jsonb,
    week_30 jsonb,
    week_31 jsonb,
    week_32 jsonb,
    week_33 jsonb,
    week_34 jsonb,
    week_35 jsonb,
    week_36 jsonb,
    week_37 jsonb,
    week_38 jsonb,
    week_39 jsonb,
    week_40 jsonb,
    week_41 jsonb,
    week_42 jsonb,
    week_43 jsonb,
    week_44 jsonb,
    week_45 jsonb,
    week_46 jsonb,
    week_47 jsonb,
    week_48 jsonb,
    week_49 jsonb,
    week_50 jsonb,
    week_51 jsonb,
    week_52 jsonb,
    week_53 jsonb
);

-- 5. example (opcjonalna)
CREATE TABLE IF NOT EXISTS public.example (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text text NOT NULL
);

-- Uprawnienia (anon, authenticated, service_role – typowe dla Supabase)
ALTER TABLE public.boats_list ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.boat_availability_2025 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.boat_availability_2026 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.boat_availability_2027 ENABLE ROW LEVEL SECURITY;

-- Polityki: odczyt dla wszystkich (dostosuj pod auth, jeśli potrzeba)
CREATE POLICY "Allow public read boats_list" ON public.boats_list FOR SELECT USING (true);
CREATE POLICY "Allow public read boat_availability_2025" ON public.boat_availability_2025 FOR SELECT USING (true);
CREATE POLICY "Allow public read boat_availability_2026" ON public.boat_availability_2026 FOR SELECT USING (true);
CREATE POLICY "Allow public read boat_availability_2027" ON public.boat_availability_2027 FOR SELECT USING (true);

-- Tabela users (User Management – import z users.csv)
CREATE TABLE IF NOT EXISTS public.users (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    email text NOT NULL UNIQUE,
    first_name text NOT NULL DEFAULT '',
    last_name text NOT NULL DEFAULT '',
    role text NOT NULL DEFAULT 'user' CHECK (role IN ('admin', 'manager', 'user')),
    email_verified boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    last_login_at timestamptz
);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow service role read users" ON public.users FOR SELECT USING (true);
CREATE POLICY "Allow service role insert users" ON public.users FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow service role update users" ON public.users FOR UPDATE USING (true);
CREATE POLICY "Allow service role delete users" ON public.users FOR DELETE USING (true);

-- Tabela notes (Notes Management – przypisane do usera, import z notes.csv)
CREATE TABLE IF NOT EXISTS public.notes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    notes text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notes_user_id ON public.notes(user_id);
ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow service role read notes" ON public.notes FOR SELECT USING (true);
CREATE POLICY "Allow service role insert notes" ON public.notes FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow service role update notes" ON public.notes FOR UPDATE USING (true);
CREATE POLICY "Allow service role delete notes" ON public.notes FOR DELETE USING (true);
