export type SingleBoatParameters = {
  max_sleeps: number;
  max_people: number;
  allowed_people: number;
  single_cabins: number;
  double_cabins: number;
  triple_cabins: number;
  quadruple_cabins: number;
  cabins: number;
  cabins_with_bunk_bed: number;
  saloon_sleeps: number;
  crew_sleeps: number;
  toilets: number;
  electric_toilets: number;
  length: number;
  beam: number;
  draft: number;
  year: number;
  renovated_year: number;
  sail_renovated_year: number;
  engine_power: number;
  number_engines: number;
  total_engine_power: number;
  engine: string;
  fuel: number;
  cruising_consumption: number;
  maximum_speed: number;
  water_tank: number;
  waste_tank: number;
  single_cabins_outdoor_entrance: false;
  single_cabins_indoor_entrance: false;
};

export type USP = { name: string; icon: string; provider: string };
export type ItemCount = { _id: number; count: number };
export type NamedItemCount = {
  _id: string;
  count: number;
  name: string;
};
export type ManufacturerNamedItemCount = {
  count: number;
  manufacturer: string;
  _id: string;
  name: string;
};
export type EmptyObjectCancellationInsurance = Record<string, any>;
export type EmptyObjectRestrictions_covered = Record<string, any>;
export type EmptyObjectFreeBerths = Record<string, any>;

export type CharterRank = {
  place: number;
  country: string;
  score: number;
  out_of: number;
  count: number;
};
export type FilterBoatSearched = {
  price: ItemCount[];
  cabins: ItemCount[];
  singleCabins: ItemCount[];
  doubleCabins: ItemCount[];
  tripleCabins: ItemCount[];
  quadrupleCabins: ItemCount[];
  cabinsWithBunkBed: ItemCount[];
  reviewScore: ItemCount[];
  toilets: ItemCount[];
  hasElectricToilets: ItemCount[];
  charter: NamedItemCount[];
  manufacturer: NamedItemCount[];
  maxSleeps: ItemCount[];
  allowedPeople: ItemCount[];
  models: ManufacturerNamedItemCount[];
  boatLength: ItemCount[];
  year: ItemCount[];
  sail: NamedItemCount[];
  cancellation: [];
  category: NamedItemCount[];
  cockpit: NamedItemCount[];
  equipment: NamedItemCount[];
  skipper: NamedItemCount[];
  services: ItemCount[];
  licenses: NamedItemCount[];
  enginePower: ItemCount[];
  engineType: NamedItemCount[];
  price_nofilter: ItemCount[];
  cabins_nofilter: ItemCount[];
  singleCabins_nofilter: ItemCount[];
  doubleCabins_nofilter: ItemCount[];
  tripleCabins_nofilter: ItemCount[];
  quadrupleCabins_nofilter: ItemCount[];
  cabinsWithBunkBed_nofilter: ItemCount[];
  reviewScore_nofilter: ItemCount[];
  toilets_nofilter: ItemCount[];
  charter_nofilter: NamedItemCount[];
  maxSleeps_nofilter: ItemCount[];
  allowedPeople_nofilter: ItemCount[];
  manufacturer_nofilter: NamedItemCount[];
  models_nofilter: ManufacturerNamedItemCount[];
  boatLength_nofilter: ItemCount[];
  year_nofilter: ItemCount[];
  sail_nofilter: NamedItemCount[];
  category_nofilter: NamedItemCount[];
  cockpit_nofilter: NamedItemCount[];
  entertainment_nofilter: NamedItemCount[];
  equipment_nofilter: NamedItemCount[];
  skipper_nofilter: NamedItemCount[];
  enginePower_nofilter: ItemCount[];
  engineType_nofilter: NamedItemCount[];
  cancellation_nofilter: any[];
  hasElectricToilets_nofilter: ItemCount[];
  licenses_nofilter: NamedItemCount[];
  services_nofilter: ItemCount[];
};
export type SingleBoatDetails = {
  _id: string;
  slug: string;
  parameters: SingleBoatParameters;
  vat_excluded: boolean;
  old_id: number;
  views: number;
  title: string;
  manufacturer: string;
  model: string;
  category: string;
  category_slug: string;
  illustrated: boolean;
  marina: string;
  coordinates: [number, number];
  country: string;
  region: string;
  city: string;
  flag: string;
  captain: string;
  sail: string;
  engineType: string;
  usp: USP[];
  cancellationInsurance: EmptyObjectCancellationInsurance;
  totalReviews: number;
  lastCustomer: string;
  rank: number;
  newboat: boolean;
  reviewsScore: number;
  cancellations: string | null;
  thumb: string;
  main_img: string;
  boataroundExtra: boolean;
  charterLoyalty: boolean;
  additional_specials: any[];
  featuredUsp: USP;
  restrictions_covered: EmptyObjectRestrictions_covered;
  freeBerths: EmptyObjectFreeBerths;
  charter: string;
  charter_logo: string;
  charter_id: string;
  charter_rank: CharterRank;
  prepayment: number;
  guarantee_date: string | null;
  priceFrom: number;
  discount: number | null;
  loyaltyDiscount: number;
  currency: string;
  isSmartDeal: boolean;
  preferred_program: boolean;
};
